server.port=${PORT:8081}

#DB settings-------------------------------------------------------------------------------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#QDRANT SETTINGS------------------------------------------------------------------------------------------------------

qdrant.url=${QDRANT_URL}
qdrant.api-key=${QDRANT_API_KEY}
qdrant.host=${QDRANT_HOST}

#S3 Settings---------------------------------------------------------------------------------------------------------
storage.bucket-name=${S3_BUCKET_NAME}
storage.endpoint=${S3_STORAGE_ENDPOINT}
storage.region=${S3_STORAGE_REGION}
storage.access-key=${S3_API_KEY_ID}
storage.secret-key=${S3_API_KEY}

#KAFKA SETTINGS----------------------------------------------------------------------------------------------------------------
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
spring.kafka.properties.ssl.truststore.password=${KAFKA_TRUSTSTORE_PASSWORD}
spring.kafka.properties.ssl.truststore.location=${KAFKA_TRUSTSTORE_LOCATION}

#JINA SETTINGS ------------------------------------------------------------------------------------------------------------------
jina.api-key=${JINA_API_KEY}

#OPEN AI SETTINGS---------------------------------------------------------------------------------------------------------------------
spring.ai.openai.api-key=${OPEN_AI_API_KEY}
#OTHER -------------------------------------------------------------------------------------------------------------------------
jwt.secret=${JWT_SECRET}
frontend.url=${FRONTEND_URL}
cookie.secure=${COOKIE_SECURE}
cookie.same-site=${COOKIE_SAME_SITE}
backend.url=${BACKEND_URL}


