server.port=8081

spring.ai.openai.api-key=${OPEN_AI_API_KEY}

qdrant.url=${QDRANT_URL}
qdrant.api-key=${QDRANT_API_KEY}
qdrant.host=${QDRANT_HOST}
qdrant.port=6334
spring.ai.openai.embedding.options.model=text-embedding-3-small